### ISSUE TITLE
Feat: #10  메인(택시 호출) 페이지 만들기

### ISSUE THREAD

**Issue by seung-in-Yoo** [likelion-inha-hackathon-2/Summerthon-FE#10]
![택시 호출](https://github.com/likelion-inha-hackathon-2/Summerthon-FE/assets/144124353/43298b35-627e-4d6b-8e89-9cbe7e175e66)

## 🎯 목적
메인페이지로 택시 호출 관련 페이지 -> 택시 호출 방법 선택,호출 메인, 택시 호출중 , 호출 완료, 호출 실패 페이지 만들기

## ✅ 완료할 일
메인 (택시 호출 방법 선택 및 긴급 호출하기) 페이지(`Main`) 만들기
- [x]  Header(오른쪽에 내 정보 글씨 적혀있는거)
- [x]  텍스트(도움말,택시 예상 도착 시간)
- [x]  Taxi icon, QR icon
- [x]  텍스트 및 Emergency call icon 

호출 메인 (`Call`) 페이지 만들기
- [x]  Header(오른쪽에 내 정보 글씨 적혀있는거)
- [x]  택시 호출 텍스트
- [x] 출발지,도착지 input 
- [x] map-basic icon
- [x] call-cancel icon

택시 호출하기 (Taxi_Call) 페이지 만들기
- [x]  Header(오른쪽에 내 정보 글씨 적혀있는거)
- [x] 호출중 텍스트
- [x] 출발지,도착지 input 
- [x] map-basic icon
- [x] call-cancel icon

택시 호출 성공 (Call_Success) 페이지 만들기
- [x]  Header(오른쪽에 내 정보 글씨 적혀있는거)
- [x] 호출완료 텍스트
- [x] 출발지,도착지 input 
- [x] map-basic icon
- [x] call-cancel icon

**Comment by abyss-s** [comment]
이거 그냥 Call 페이지에서 하나로 통일해야 할 것 같아요..! 만들고 있긴 한데 내일 좀 더 수정해볼게요.
